# Generated by Django 2.1.4 on 2018-12-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Motel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('horario', models.CharField(blank=True, max_length=15, null=True)),
                ('tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motel.Distrito')),
            ],
        ),
    ]
